name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AZ_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZ_CLIENT_SECRET: ${{secrets.AZURE_SECRET}}
      AZ_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      AZ_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    environment: dev

    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init -backend-config="dev.backend.tfvars"
        
      - name: Terraform Plan
        run: terraform plan -input=false
  
      - name: Terraform Apply
        if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
