name: 'Terraform'

on:
  push:
    branches: 
    - "main" 
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      PUBLISHER_NAME: ${{ vars.PUBLISHER_NAME }}
      PUBLISHER_EMAIL: ${{ vars.PUBLISHER_EMAIL }}

    environment: dev

    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.4

      - name: Azure Login action
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init -backend-config="dev.backend.tfvars"
        
      - name: Terraform Plan
        run: terraform plan -var "publisher_email=$PUBLISHER_EMAIL" -var "publisher_name=$PUBLISHER_NAME" -input=false 
  
      - name: Terraform Apply
        run: terraform apply -var "publisher_email=$PUBLISHER_EMAIL" -var "publisher_name=$PUBLISHER_NAME" -auto-approve -input=false
